#if NET7_0_OR_GREATER
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;

namespace PayPalCheckoutSdk
{
    /// <summary>
    /// Experimental!!
    /// </summary>
    [JsonSerializable(typeof(PayPalCheckoutSdk.Core.AddressDetails), TypeInfoPropertyName = "Core_AddressDetails")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Core.AddressPortable), TypeInfoPropertyName = "Core_AddressPortable")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Core.ApplicationContext), TypeInfoPropertyName = "Core_ApplicationContext")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Core.BillingCycle), TypeInfoPropertyName = "Core_BillingCycle")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Core.Card), TypeInfoPropertyName = "Core_Card")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Core.Error), TypeInfoPropertyName = "Core_Error")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Core.ErrorDetails), TypeInfoPropertyName = "Core_ErrorDetails")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Core.Frequency), TypeInfoPropertyName = "Core_Frequency")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Core.LinkDescription), TypeInfoPropertyName = "Core_LinkDescription")]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Core.LinkSchema))]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Core.Media), TypeInfoPropertyName = "Core_Media")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Core.Money), TypeInfoPropertyName = "Core_Money")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Core.Name), TypeInfoPropertyName = "Core_Name")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Core.NetAmountBreakdownItem), TypeInfoPropertyName = "Core_NetAmountBreakdownItem")]
    [JsonSerializable(typeof(List<PayPalCheckoutSdk.Core.Patch<string>>))]
    //[JsonSerializable(typeof(List<>))]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Core.PaymentMethod), TypeInfoPropertyName = "Core_PaymentMethod")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Core.PaymentPreferences), TypeInfoPropertyName = "Core_PaymentPreferences")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Core.PaymentSource), TypeInfoPropertyName = "Core_PaymentSource")]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Core.PaypalEnvironment))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Core.PaypalHttpClient))]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Core.PhoneWithType), TypeInfoPropertyName = "Core_PhoneWithType")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Core.PhoneWithTypePhone), TypeInfoPropertyName = "Core_PhoneWithTypePhone")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Core.PricingScheme), TypeInfoPropertyName = "Core_PricingScheme")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Core.PricingTier), TypeInfoPropertyName = "Core_PricingTier")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Core.ShippingDetail), TypeInfoPropertyName = "Core_ShippingDetail")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Core.ShippingOption), TypeInfoPropertyName = "Core_ShippingOption")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Core.Taxes), TypeInfoPropertyName = "Core_Taxes")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Core.Token), TypeInfoPropertyName = "Core_Token")]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Core.UserAgent))]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Core.Version), TypeInfoPropertyName = "Core_Version")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.AmountBreakdown), TypeInfoPropertyName = "Orders_AmountBreakdown")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.AmountWithBreakdown), TypeInfoPropertyName = "Orders_AmountWithBreakdown")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.Authorization), TypeInfoPropertyName = "Orders_Authorization")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.AuthorizationStatusDetails), TypeInfoPropertyName = "Orders_AuthorizationStatusDetails")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.AuthorizeRequest), TypeInfoPropertyName = "Orders_AuthorizeRequest")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.Capture), TypeInfoPropertyName = "Orders_Capture")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.CaptureStatusDetails), TypeInfoPropertyName = "Orders_CaptureStatusDetails")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.Item), TypeInfoPropertyName = "Orders_Item")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.MerchantPayableBreakdown), TypeInfoPropertyName = "Orders_MerchantPayableBreakdown")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.MerchantReceivableBreakdown), TypeInfoPropertyName = "Orders_MerchantReceivableBreakdown")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.Order), TypeInfoPropertyName = "Orders_Order")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.OrderActionRequest), TypeInfoPropertyName = "Orders_OrderActionRequest")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.OrderCaptureRequest), TypeInfoPropertyName = "Orders_OrderCaptureRequest")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.OrderRequest), TypeInfoPropertyName = "Orders_OrderRequest")]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Orders.OrdersAuthorizeRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Orders.OrdersCaptureRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Orders.OrdersCreateRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Orders.OrdersGetRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Orders.OrdersPatchRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Orders.OrdersValidateRequest))]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.Payee), TypeInfoPropertyName = "Orders_Payee")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.PayeeBase), TypeInfoPropertyName = "Orders_PayeeBase")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.PayeeDisplayable), TypeInfoPropertyName = "Orders_PayeeDisplayable")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.Payer), TypeInfoPropertyName = "Orders_Payer")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.PaymentCollection), TypeInfoPropertyName = "Orders_PaymentCollection")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.PaymentInstruction), TypeInfoPropertyName = "Orders_PaymentInstruction")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.Phone), TypeInfoPropertyName = "Orders_Phone")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.PhoneWithType), TypeInfoPropertyName = "Orders_PhoneWithType")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.PurchaseUnit), TypeInfoPropertyName = "Orders_PurchaseUnit")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.PurchaseUnitRequest), TypeInfoPropertyName = "Orders_PurchaseUnitRequest")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.Refund), TypeInfoPropertyName = "Orders_Refund")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.RefundStatusDetails), TypeInfoPropertyName = "Orders_RefundStatusDetails")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.SellerProtection), TypeInfoPropertyName = "Orders_SellerProtection")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Orders.TaxInfo), TypeInfoPropertyName = "Orders_TaxInfo")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Payments.Authorization), TypeInfoPropertyName = "Payments_Authorization")]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Payments.AuthorizationsCaptureRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Payments.AuthorizationsGetRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Payments.AuthorizationsReauthorizeRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Payments.AuthorizationsVoidRequest))]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Payments.Capture), TypeInfoPropertyName = "Payments_Capture")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Payments.CaptureRequest), TypeInfoPropertyName = "Payments_CaptureRequest")]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Payments.CapturesGetRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Payments.CapturesRefundRequest))]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Payments.ExchangeRate), TypeInfoPropertyName = "Payments_ExchangeRate")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Payments.MerchantBase), TypeInfoPropertyName = "Payments_MerchantBase")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Payments.MerchantPayableBreakdown), TypeInfoPropertyName = "Payments_MerchantPayableBreakdown")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Payments.MerchantReceivableBreakdown), TypeInfoPropertyName = "Payments_MerchantReceivableBreakdown")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Payments.PaymentInstruction), TypeInfoPropertyName = "Payments_PaymentInstruction")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Payments.PlatformFee), TypeInfoPropertyName = "Payments_PlatformFee")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Payments.ReauthorizeRequest), TypeInfoPropertyName = "Payments_ReauthorizeRequest")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Payments.Refund), TypeInfoPropertyName = "Payments_Refund")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Payments.RefundRequest), TypeInfoPropertyName = "Payments_RefundRequest")]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Payments.RefundsGetRequest))]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Payments.SellerProtection), TypeInfoPropertyName = "Payments_SellerProtection")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Payments.StatusDetails), TypeInfoPropertyName = "Payments_StatusDetails")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Products.Product), TypeInfoPropertyName = "Products_Product")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Products.ProductCollection), TypeInfoPropertyName = "Products_ProductCollection")]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Products.ProductGetRequest))]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Products.ProductRequest), TypeInfoPropertyName = "Products_ProductRequest")]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Products.ProductsCreateRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Products.ProductsGetRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Products.ProductsPatchRequest))]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.AmountWithBreakdown), TypeInfoPropertyName = "Subscriptions_AmountWithBreakdown")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.CycleExecution), TypeInfoPropertyName = "Subscriptions_CycleExecution")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.FailedPaymentDetails), TypeInfoPropertyName = "Subscriptions_FailedPaymentDetails")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.LastPaymentDetails), TypeInfoPropertyName = "Subscriptions_LastPaymentDetails")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.Plan), TypeInfoPropertyName = "Subscriptions_Plan")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.PlanCollection), TypeInfoPropertyName = "Subscriptions_PlanCollection")]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.PlanGetRequest))]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.PlanRequest), TypeInfoPropertyName = "Subscriptions_PlanRequest")]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.PlansActivateRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.PlansChangePricingRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.PlansCreateRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.PlansDeactivateRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.PlansGetRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.PlansPatchRequest))]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.Subscriber), TypeInfoPropertyName = "Subscriptions_Subscriber")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.Subscription), TypeInfoPropertyName = "Subscriptions_Subscription")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.SubscriptionActivateRequest), TypeInfoPropertyName = "Subscriptions_SubscriptionActivateRequest")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.SubscriptionBillingInfo), TypeInfoPropertyName = "Subscriptions_SubscriptionBillingInfo")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.SubscriptionCancelRequest), TypeInfoPropertyName = "Subscriptions_SubscriptionCancelRequest")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.SubscriptionCaptureRequest), TypeInfoPropertyName = "Subscriptions_SubscriptionCaptureRequest")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.SubscriptionCollection), TypeInfoPropertyName = "Subscriptions_SubscriptionCollection")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.SubscriptionRequest), TypeInfoPropertyName = "Subscriptions_SubscriptionRequest")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.SubscriptionReviseRequest), TypeInfoPropertyName = "Subscriptions_SubscriptionReviseRequest")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.SubscriptionReviseResponse), TypeInfoPropertyName = "Subscriptions_SubscriptionReviseResponse")]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.SubscriptionsActivateRequest))]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.SubscriptionSaveRequest), TypeInfoPropertyName = "Subscriptions_SubscriptionSaveRequest")]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.SubscriptionsCancelRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.SubscriptionsCaptureRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.SubscriptionsCreateRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.SubscriptionsGetRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.SubscriptionsGetTransactionsRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.SubscriptionsPatchRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.SubscriptionsReviseRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.SubscriptionsSuspendRequest))]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.SubscriptionSuspendRequest), TypeInfoPropertyName = "Subscriptions_SubscriptionSuspendRequest")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.Transaction), TypeInfoPropertyName = "Subscriptions_Transaction")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.TransactionList), TypeInfoPropertyName = "Subscriptions_TransactionList")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Subscriptions.UpdatePricingSchemeRequest), TypeInfoPropertyName = "Subscriptions_UpdatePricingSchemeRequest")]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.AnchorType))]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.Event), TypeInfoPropertyName = "Webhooks_Event")]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.EventGetRequest))]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.EventList), TypeInfoPropertyName = "Webhooks_EventList")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.EventResend), TypeInfoPropertyName = "Webhooks_EventResend")]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.EventResendRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.EventsGetRequest))]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.EventSimulate), TypeInfoPropertyName = "Webhooks_EventSimulate")]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.EventSimulateRequest))]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.EventType), TypeInfoPropertyName = "Webhooks_EventType")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.EventTypeList), TypeInfoPropertyName = "Webhooks_EventTypeList")]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.EventTypesAvailableGetRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.EventTypesGetRequest))]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.Lookup), TypeInfoPropertyName = "Webhooks_Lookup")]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.LookupCreateRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.LookupDeleteRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.LookupGetRequest))]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.LookupList), TypeInfoPropertyName = "Webhooks_LookupList")]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.LookupsGetRequest))]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.ResourceVersion), TypeInfoPropertyName = "Webhooks_ResourceVersion")]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.VerificationStatus))]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.VerifyWebhookSignature), TypeInfoPropertyName = "Webhooks_VerifyWebhookSignature")]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.VerifyWebhookSignatureRequest))]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.VerifyWebhookSignatureResponse), TypeInfoPropertyName = "Webhooks_VerifyWebhookSignatureResponse")]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.Webhook), TypeInfoPropertyName = "Webhooks_Webhook")]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.WebhookCreateRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.WebhookDeleteRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.WebhookGetRequest))]
    [JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.WebhookList), TypeInfoPropertyName = "Webhooks_WebhookList")]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.WebhookPatchRequest))]
    //[JsonSerializable(typeof(PayPalCheckoutSdk.Webhooks.WebhooksGetRequest))]

    public partial class JsonSourceGenerator : JsonSerializerContext
    {
    }
}
#endif
